#ifndef __NEPI_EDGE_ERRORS_H
#define __NEPI_EDGE_ERRORS_H

typedef enum NEPI_EDGE_RET
{
  NEPI_EDGE_RET_OK = 0,
  NEPI_EDGE_RET_UNINIT_OBJ = -1,
  NEPI_EDGE_RET_MALLOC_ERR = -2,
  NEPI_EDGE_RET_WRONG_OBJ_TYPE = -3,
  NEPI_EDGE_RET_ARG_OUT_OF_RANGE = -4,
  NEPI_EDGE_RET_ARG_TOO_LONG = -5,
  NEPI_EDGE_RET_FILE_OPEN_ERR = -6,
  NEPI_EDGE_RET_INCOMPLETE_OBJ = -7,
  NEPI_EDGE_RET_REQUIRED_FIELD_MISSING = -8,
  NEPI_EDGE_RET_FILE_PERMISSION_ERR = -9,
} NEPI_EDGE_RET_t;

#endif //__NEPI_EDGE_ERRORS_H
